config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  root 'home#index'

  devise_for :users

  resources :posts, except: [:index, :show]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include SimpleHashtag::Hashtaggable
  
  belongs_to :user

  validates :body, :presence => true

  scope :by_date, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts

  validates :name, :presence => true

  validates_uniqueness_of :email

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :avatar) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def index
    @hashtags = SimpleHashtag::Hashtag.all
  end

  def show
    @hashtag = SimpleHashtag::Hashtag.find_by_name(params[:hashtag])
    @hashtagged = @hashtag.hashtaggables if @hashtag
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :js

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(posts_params)
    if !@post.save
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(posts_params)
      flash[:notice] = "Chip edited!"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Chip deleted!"
    redirect_to root_path
  end

private
  def posts_params
    params.require(:post).permit(:body, :user_id)
  end
end


# Create Without Responder:
# @post = current_user.posts.new(posts_params)
# if @post.save
#   flash[:notice] = "Chip saved!"
#   respond_to do |format|
#     format.html { redirect_to root_path }
#     format.js
#   end
# else
#   render :new
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def linkify_hashtags(hashtaggable_content)
    regex = SimpleHashtag::Hashtag::HASHTAG_REGEX
    hashtagged_content = hashtaggable_content.to_s.gsub(regex) do
      link_to($&, hashtag_path($2), {class: :hashtag})
    end
    hashtagged_content.html_safe
  end

  def render_hashtaggable(hashtaggable)
    klass        = hashtaggable.class.to_s.underscore
    view_dirname = klass.pluralize
    partial      = klass
    render "#{view_dirname}/#{partial}", {klass.to_sym => hashtaggable}
  end
end

app/views/hashtags/index.html.erb
<h1>Hashtags</h1>
<ul>
<% @hashtags.each do |hashtag| %>
  <li><%= link_to hashtag.name, hashtag_path(hashtag.name) %></li>
<% end -%>
</ul>

app/views/hashtags/show.html.erb
<h1><%= params[:hashtag] %></h1>
<% if @hashtagged %>
  <% @hashtagged.each do |hashtagged| %>
    <%= render_hashtaggable hashtagged %>
  <% end -%>
<% else -%>
  <p>There is no match for the <em><%= params[:hashtag] %></em> hashtag.</p>
<% end -%>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-12">
    <p><%= link_to new_post_path, remote: true, id: "new_chip", class: "btn btn-sm btn-info" do %><i class="fa fa-pencil"></i> New Post<% end %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @posts.any? %>
      <hr>
      <h2>Posts:</h2>
      <div id="posts">
        <%= render @posts %>
      </div>
    <% else %>
      <h2 id="no_posts">No posts, yet!</h2>
      <div id="posts"></div>
    <% end %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="well">
    <h5>Please fix the following errors:</h5>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chipper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand", id: "brand" do %>Chipper<% end %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a id="welcome">Hello, <strong><%= current_user.name %></strong>!</a></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post, remote: true do |f| %>
  <ul class="formList list-unstyled">

    <li>
      <%= f.label :body %><br>
      <%= f.text_area :body, :cols => "60", :rows => "10" %>
    </li>

    <li class="submit">
      <%= f.submit "Submit", class: "btn btn-sm btn-success" %>
    </li>
  </ul>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 well">
    <div class="col-md-2">
      <%= image_tag post.user.avatar.url(:thumb) %>
    </div>
    <div class="col-md-8">
      <p>
        <%= post.user.name %> sez:<br>
        <span class="post-body"><%= post.body %></span><br>
        <small><%= post.created_at.to_formatted_s(:long_ordinal) %></small>
      </p>
    </div>
    <div class="col-md-2 text-right">
      <% if post.user == current_user %>
        <p>
          <%= link_to edit_post_path(post) do %><i class="fa fa-cog"></i> Edit Post<% end %><br>
          <%= link_to post_path(post), :data => {:confirm => "Do you really want to delete this post?", :method => "delete"} do %><i class="fa fa-trash-o"></i> Delete Post<% end %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
$('#new_post').remove();
$('#new_chip').show();
$('#no_posts').hide();
$('#posts').prepend('<%= j render(@post) %>');

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Edit Post</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>New Post</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/posts/new.js.erb
$('#new_chip').hide().after('<%= j render("form") %>');